# Generated by Django 3.2.16 on 2024-01-12 20:39

import apps.player.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('players', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Player List',
                'verbose_name_plural': 'Player Lists',
            },
        ),
        migrations.CreateModel(
            name='UserPlayerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[apps.player.models.validate_max_player_lists_per_user])),
            ],
            options={
                'verbose_name': 'User Player List',
                'verbose_name_plural': 'User Player Lists',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Not specified')], default='n', max_length=1)),
                ('stars', models.DecimalField(blank=True, choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5')], decimal_places=1, max_digits=2, null=True)),
                ('attack', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('defense', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('resistance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('player_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerlist', validators=[apps.player.models.validate_max_players_per_list])),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'unique_together': {('position', 'player_list')},
            },
        ),
    ]
