# Generated by Django 3.2.16 on 2024-01-17 19:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerlist'),
        ),
        migrations.AlterField(
            model_name='playerlist',
            name='players',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
