# Generated by Django 3.2.16 on 2024-01-15 02:50

import apps.draw.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('player', '0002_alter_player_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('last_modified', models.DateTimeField()),
                ('type', models.CharField(choices=[('n', 'Normal'), ('g', 'Gender'), ('s', 'Skill Level'), ('a', 'Advanced')], default='n', max_length=1)),
                ('player_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerlist')),
                ('team_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teamlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[apps.draw.models.validate_max_draws_per_user])),
            ],
            options={
                'verbose_name': 'Draw',
                'verbose_name_plural': 'Draws',
            },
        ),
    ]
