# Generated by Django 3.2.16 on 2024-01-17 19:29

import apps.draw.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draw',
            name='slug',
            field=models.SlugField(default=apps.draw.models.get_unique_slug, unique=True),
        ),
    ]
