# Generated by Django 3.2.16 on 2024-01-13 07:40

import apps.team.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('teams', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team List',
                'verbose_name_plural': 'Team Lists',
            },
        ),
        migrations.CreateModel(
            name='UserTeamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teamlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[apps.team.models.validate_max_team_lists_per_user])),
            ],
            options={
                'verbose_name': 'User Team List',
                'verbose_name_plural': 'User Team Lists',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField()),
                ('team_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teamlist', validators=[apps.team.models.validate_max_teams_per_list])),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'unique_together': {('position', 'team_list')},
            },
        ),
    ]
