# Generated by Django 3.2.16 on 2024-01-17 19:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teamlist'),
        ),
        migrations.AlterField(
            model_name='teamlist',
            name='teams',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
